services:
  - type: web
    name: beer-clicker-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: beer-clicker-db
          property: connectionString
      - key: BOT_TOKEN
        value: <7574810395:AAH7-PqxhdvqBU9FbW8nkX1w1RLMQBdWf-4>
    region: frankfurt
    plan: free

databases:
  - name: beer-clicker-db
    region: frankfurt
